### ISSUE TITLE
cost threshold

### ISSUE THREAD

**Issue by psteadman** [jkenney9a/Networks#3]
Hey wheres the cost threshold approach, right now only p value is there?

**Comment by jkenney9a** [comment]
Good point, it's not explicitly built into the functions. You would calculate the cost threshold yourself from the adjacency/weight matrix (e.g, using the quantile function) and then pass an 'r' value threshold by changing the thresh.param to 'r'. But it would be worth having that as a threshold option. I'll look at add that in the future.
